project:
  name: aspect-workforce-connect-integration
  owner: support@alvaria.com
  package_lambda: false
  regions:
  - us-east-1
tests:
  default:
    parameters:
      FirehoseStreamName: tcat-$[taskcat_random-string]
      SignedOutStatuses: ''
      NumSQSQueues: 1
      LambdaConfigLocation: tab
      ConnectS3Bucket: tcat-$[taskcat_random-string]
      ConnectS3Prefix: tcat-$[taskcat_random-string]/
      ConnectS3KmsArn: ''
      AHGFilterLevel: 0
      AHGFilterValues: ''
      AuthorizationMode: User
      SourceAwsAccountId: ''
      ExternalId: ''
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - us-east-1
    - us-west-2
    - af-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - eu-central-1
    - eu-west-2
    template: templates/aspect-wfm-ap-and-rta-create-stream.template.yaml
