---
AWSTemplateFormatVersion: "2010-09-09"
Description: Aspect Workforce Connect RTA CloudFormation template with associated Kinesis stream
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Aspect Workforce Configuration
        Parameters:
          - NumSQSQueues
          - LambdaConfigLocation
      - Label:
          default: Amazon Connect Configuration
        Parameters:
          - AHGFilterLevel
          - AHGFilterSeparator
          - AHGFilterValues
      - Label:
          default: IAM Configuration
        Parameters:
          - AuthorizationMode
          - SourceAwsAccountId
          - ExternalId
      - Label:
          default: Deployment configuration
        Parameters:
          - DeploymentS3BucketName
          - DeploymentS3KeyPrefix
    ParameterLabels:
      NumSQSQueues:
        default: Number of SQS Queues
      LambdaConfigLocation:
        default: Write to SQS Flag Location
      AHGFilterLevel:
        default: Agent Hierarchy Group Level
      AHGFilterSeparator:
        default: Agent Hierarchy Group filter value separator
      AHGFilterValues:
        default: Agent Hierarchy Group filter matching values
      AuthorizationMode:
        default: Authorization Mode
      SourceAwsAccountId:
        default: Source AWS Account ID
      ExternalId:
        default: External ID
      DeploymentS3BucketName:
        default: Deployment S3 Bucket Name
      DeploymentS3KeyPrefix:
        default: Deployment S3 Key Prefix
Parameters:
  NumSQSQueues:
    Description: The number of SQS queues to create (must be between 1 and 10). Creating additional SQS queues can reduce the latency of state changes.
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: Must be a number between 1 and 10.
  LambdaConfigLocation:
    Description: Once RTA reads an initial set of states from the agent event DynamoDB table, it toggles a Write to
      SQS flag to ensure that agent events are written to the SQS queue(s). This setting controls where that Write
      to SQS flag is stored either in an environment variable of the RTA Lambda (env) or in a configuration DynamoDB
      table (table). Storing this flag in an environment variable of the Lambda requires less overhead, but requires
      greater permissions for the RTA user. Storing this flag in a configuration DynamoDB table requires fewer
      permissions for the RTA user, but requires an additional DyanmoDB read each time the RTA Lambda executes. By
      default, this flag will be stored in an environment variable of the RTA Lambda.
    Type: String
    Default: env
    AllowedValues:
      - env
      - tab
  AHGFilterLevel:
    Description: The Agent Hierarchy Group Level on which agent events should be filtered (must be between 0 and 5).
      Configuring a value of 0 disables filtering. Configuring a value between 1 and 5 means that agent events will
      be filtered based on that Agent Hierarchy Group Level.
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 5
    ConstraintDescription: Must be a number between 0 and 5.
  AHGFilterSeparator:
    Description: Character used to separate matching values listed in AHGFilterValues. You should configure a separator
      character that does not appear in any of the individual matching values.
    Type: String
    Default: ","
    MinLength: 1
    MaxLength: 1
  AHGFilterValues:
    Description: An optional list of matching Agent Hierarchy Group Level values. If you enable Agent Hierarchy Group
      filtering, any agent events with an Agent Hierarchy Group Level value matching one of the values listed here will
      be sent on to Real-Time Adherence and any agent events that do not match the filter will be discarded. Matching
      values should be separated with the character configured in AHGFilterSeparator.
    Type: String
  AuthorizationMode:
    Type: String
    Description: Select User to create an IAM User for RTA. Select Role to create
      an IAM Role for RTA. If RTA is running outside of AWS, you should
      select User. If RTA is running inside AWS, you should select Role.
    Default: User
    AllowedValues:
      - User
      - Role
  SourceAwsAccountId:
    Type: String
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: If Authorization Mode is User, Source AWS Account ID should be
      blank. If Authorization Mode is Role, Source AWS Account ID should be a 12-digit
      number.
    Description: Optional AWS account ID to include in the trust policy for the IAM Role.
      The AWS account ID should match the AWS account from which RTA will assume
      the role. This parameter is required when Authorization Mode is Role. This parameter 
      will be ignored when Authorization Mode is User.
  ExternalId:
    Type: String
    AllowedPattern: '^[0-9a-zA-Z+=,.@:\/-]*$'
    ConstraintDescription: 'External ID values can include numbers, lowercase letters, uppercase letters, and the following special characters: + = , . @ : / -'
    Description: Optional external ID to include in the trust policy for the IAM Role. If
      Authorization Mode is Role, the role will be configured to require this external ID. 
      You will need to configure RTA to supply this external ID when it assumes the 
      role. If Authorization Mode is User, this parameter will be ignored.
  DeploymentS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Deployment bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aspect-workforce
    Description:
      S3 bucket name for the deployment assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  DeploymentS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription:
      Deployment key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: aspect-workforce-connect-integration/
    Description:
      S3 key prefix for the deployment assets. Deployment key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
Resources:
  CreateStreamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DeploymentS3Bucket}.s3.${AWS::URLSuffix}/${DeploymentS3KeyPrefix}templates/create-kinesis-stream.template.yaml"
  WorkloadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DeploymentS3Bucket}.s3.${AWS::URLSuffix}/${DeploymentS3KeyPrefix}templates/aspect-wfm-rta.template.yaml"
      Parameters:
        NumSQSQueues: !Ref NumSQSQueues
        LambdaConfigLocation: !Ref LambdaConfigLocation
        AHGFilterLevel: !Ref AHGFilterLevel
        AHGFilterSeparator: !Ref AHGFilterSeparator
        AHGFilterValues: !Ref AHGFilterValues
        AuthorizationMode: !Ref AuthorizationMode
        SourceAwsAccountId: !Ref SourceAwsAccountId
        ExternalId: !Ref ExternalId
        DeploymentS3BucketName: !Ref DeploymentS3BucketName
        DeploymentS3KeyPrefix: !Ref DeploymentS3KeyPrefix
        AgentEventStreamArn:
          Fn::GetAtt:
            - CreateStreamStack
            - Outputs.KinesisStreamArn
        AgentEventStreamKmsArn: ''
Outputs:
  AgentEventStreamArn:
    Value:
      Fn::GetAtt:
        - CreateStreamStack
        - Outputs.KinesisStreamArn
  DynamoDbTableName:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.DynamoDbTableName
  ConfigTableName:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.ConfigTableName
  SqsQueueUrl1:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl1
  SqsQueueUrl2:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl2
  SqsQueueUrl3:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl3
  SqsQueueUrl4:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl4
  SqsQueueUrl5:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl5
  SqsQueueUrl6:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl6
  SqsQueueUrl7:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl7
  SqsQueueUrl8:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl8
  SqsQueueUrl9:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl9
  SqsQueueUrl10:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.SqsQueueUrl10
  RTALambdaFunctionName:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.RTALambdaFunctionName
  RTAUserName:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.RTAUserName
  RTARoleARN:
    Value:
      Fn::GetAtt:
        - WorkloadStack
        - Outputs.RTARoleARN
