---
AWSTemplateFormatVersion: '2010-09-09'
Description: Aspect Workforce Agent Productivity Report Generator integration with associated Kinesis stream
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Aspect Workforce Configuration
      Parameters:
      - FirehoseStreamName
      - ApDataS3Prefix
      - StatusSeparator
      - SignedOutStatuses
    - Label:
        default: Amazon Connect Configuration
      Parameters:
      - ConnectS3Bucket
      - ConnectS3Prefix
      - ConnectS3KmsArn
    - Label:
        default: IAM Configuration
      Parameters:
        - AuthorizationMode
        - SourceAwsAccountId
        - ExternalId
    - Label:
        default: Deployment configuration
      Parameters:
      - DeploymentS3BucketName
      - DeploymentS3KeyPrefix
    ParameterLabels:
      FirehoseStreamName:
        default: Kinesis Firehose Stream Name
      ApDataS3Prefix:
        default: Agent Productivity Report Prefix
      StatusSeparator:
        default: Agent Status Name Separator
      SignedOutStatuses:
        default: Signed-Out Agent Status Names
      ConnectS3Bucket:
        default: Amazon Connect Exported Reports Bucket
      ConnectS3Prefix:
        default: Amazon Connect Exported Reports Prefix
      ConnectS3KmsArn:
        default: Amazon Connect Exported Reports Bucket KMS Key ARN
      AuthorizationMode:
        default: Authorization Mode
      SourceAwsAccountId:
        default: Source AWS Account ID
      ExternalId:
        default: External ID
      DeploymentS3BucketName:
        default: Deployment S3 Bucket Name
      DeploymentS3KeyPrefix:
        default: Deployment S3 Key Prefix
Parameters:
  FirehoseStreamName:
    Type: String
    Default: aspect-wfm-ap-kda-to-s3
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    Description: Enter the name of the Kinesis Firehose stream to create.  This
      string can include numbers, lowercase letters, uppercase letters, and hyphens
      (-). It cannot start or end with a hyphen (-).  If you have multiple Amazon
      Connect instances in your AWS account, you will need to create a Kinesis Firehose
      stream for each Amazon Connect instance and give each stream
      a unique name.  The name of the Kinesis Firehose stream determines the filenames 
      of agent productivity report files written to S3.  By default, WFM Adapter expects 
      the report files to be named based on a Kinesis Firehose stream name of "aspect-wfm-ap-kda-to-s3". 
      If you specify a different stream name, be sure to update the WFM Adapter configuration 
      for the corresponding data source to match your stream name, in the Firehose Report Mapping data
      source parameter.  Consult the WFM Adapter help for more information.
  ApDataS3Prefix:
    Type: String
    Default: OUTPUT/
    Description: Enter the prefix for Agent Productivity reports written
      to S3.  You should configure the corresponding WFM Adapter data source to match
      this value, in the Firehose Report Root Path data source parameter.
  StatusSeparator:
    Type: String
    Description: Character used to separate signed-out agents status names. You should configure a separator
      character that does not appear in any of the individual names.
    Default: ","
    MinLength: 1
    MaxLength: 1
  SignedOutStatuses:
    Type: String
    Description: Enter the list of agent status names for agent statuses that should be
      treated as signed-out in WFM. For example, an agent status named Break which agents
      use during a scheduled break would typically be listed here. Multiple signed-out
      agent status names may be listed. Names should be separated by the configured Agent
      Status Name Separator. The agent status with a Type of OFFLINE, by default named Offline,
      will always be treated as signed-out.
  ConnectS3Bucket:
    Type: String
    Description: Enter the name of the Exported reports S3 bucket of your Amazon Connect
      instance.
  ConnectS3Prefix:
    Type: String
    Default: connect/directory/Reports/Aspect/
    Description: Enter the prefix under which the exported reports read by WFM Adapter
      will be exported, in the Exported reports bucket of your Amazon Connect instance.
  ConnectS3KmsArn:
    Type: String
    Description: Optional Amazon Resource Name (ARN) of the KMS key required to decrypt
      the exported reports of your Amazon Connect instance. You should supply this ARN
      if you configured your exported reports bucket to use server-side encryption with an
      AWS Key Management Service (KMS) key. Otherwise, you should leave this parameter
      blank.
  AuthorizationMode:
    Type: String
    Description: Select User to create an IAM User for WFM Adapter. Select Role to create
      an IAM Role for WFM Adapter. If WFM Adapter is running outside of AWS, you should
      select User. If WFM Adapter is running inside AWS, you should select Role.
    Default: User
    AllowedValues:
      - User
      - Role
  SourceAwsAccountId:
    Type: String
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: If Authorization Mode is User, Source AWS Account ID should be
      blank. If Authorization Mode is Role, Source AWS Account ID should be a 12-digit
      number.
    Description: Optional AWS account ID to include in the trust policy for the IAM Role.
      The AWS account ID should match the AWS account from which WFM Adapter will assume
      the role. This parameter is required when Authorization Mode is Role. This parameter 
      will be ignored when Authorization Mode is User.
  ExternalId:
    Type: String
    AllowedPattern: '^[0-9a-zA-Z+=,.@:\/-]*$'
    ConstraintDescription: 'External ID values can include numbers, lowercase letters, uppercase letters, and the following special characters: + = , . @ : / -'
    Description: Optional external ID to include in the trust policy for the IAM Role. If
      Authorization Mode is Role, the role will be configured to require this external ID. 
      You will need to configure WFM Adapter to supply this external ID when it assumes the 
      role. If Authorization Mode is User, this parameter will be ignored.
  DeploymentS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Deployment bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aspect-workforce
    Description: S3 bucket name for the deployment assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  DeploymentS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Deployment key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: aspect-workforce-connect-integration/
    Description: S3 key prefix for the deployment assets. Deployment key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
Rules:
  ParameterDefaults:
    Assertions:
    - Assert:
        Fn::Not:
        - Fn::Equals:
          - Ref: ConnectS3Prefix
          - connect/directory/Reports/Aspect/
      AssertDescription: Replace directory with the directory name of your Amazon
        Connect instance.
  RoleRequiredParameters:
    RuleCondition: !Equals [!Ref AuthorizationMode, 'Role']
    Assertions:
    - Assert: !Not [!Equals [!Ref SourceAwsAccountId, '']]
      AssertDescription: Source AWS Account ID is required when Authorization Mode
        is Role.
    - Assert: !Not [!Equals [!Ref ExternalId, '']]
      AssertDescription: External ID is required when Authorization Mode is Role.
Resources:
  CreateStreamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${DeploymentS3BucketName}.s3.${AWS::URLSuffix}/${DeploymentS3KeyPrefix}templates/create-kinesis-stream.template.yaml'
  WorkloadStack:
    DependsOn: CreateStreamStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${DeploymentS3BucketName}.s3.${AWS::URLSuffix}/${DeploymentS3KeyPrefix}templates/aspect-wfm-ap.template.yaml'
      Parameters:
        FirehoseStreamName: !Ref FirehoseStreamName
        ApDataS3Prefix: !Ref ApDataS3Prefix
        StatusSeparator: !Ref StatusSeparator
        SignedOutStatuses: !Ref SignedOutStatuses
        ConnectS3Bucket: !Ref ConnectS3Bucket
        ConnectS3Prefix: !Ref ConnectS3Prefix
        ConnectS3KmsArn: !Ref ConnectS3KmsArn
        AuthorizationMode: !Ref AuthorizationMode
        SourceAwsAccountId: !Ref SourceAwsAccountId
        ExternalId: !Ref ExternalId
        DeploymentS3BucketName: !Ref DeploymentS3BucketName
        DeploymentS3KeyPrefix: !Ref DeploymentS3KeyPrefix
        AgentEventStreamArn:
          Fn::GetAtt:
          - CreateStreamStack
          - Outputs.KinesisStreamArn
        AgentEventStreamKmsArn: ''
Outputs:
  AgentEventStreamArn:
    Value:
      Fn::GetAtt:
      - CreateStreamStack
      - Outputs.KinesisStreamArn
  APS3BucketName:
    Value:
      Fn::GetAtt:
      - WorkloadStack
      - Outputs.APS3BucketName
  APUpdateLambdaFunctionName:
    Value:
      Fn::GetAtt:
      - WorkloadStack
      - Outputs.APUpdateLambdaFunctionName
  APKinesisLambdaFunctionName:
    Value:
      Fn::GetAtt:
      - WorkloadStack
      - Outputs.APKinesisLambdaFunctionName
  WFMAdapterUserName:
    Value:
      Fn::GetAtt:
      - WorkloadStack
      - Outputs.WFMAdapterUserName
  WFMAdapterRoleARN:
    Value:
      Fn::GetAtt:
      - WorkloadStack
      - Outputs.WFMAdapterRoleARN
...
